### ISSUE TITLE
Conside to change license to MIT

### ISSUE THREAD

**Issue by SCullman** [BarryWaluszko/Auth0_DnnProvider#2]
Please consider to change license to [MIT](https://choosealicense.com/licenses/mit/), same as DNN.

**Comment by Timo-Breumelhof** [comment]
Why, what's wrong with GPL?

**Comment by SCullman** [comment]
Currently I don't know whether the software fulfills my needs or not. I can't test, as there is no release package. Therefore I would need to download the repository, and then I may realize that it still needs some modifications to compile it. At the latest now I have to deal with the source, I also have to read and understand at least parts of it. 
Now there is a similar open source [repository ](https://github.com/jbrinkman/Auth0-Provider) targeting the same goal, but it has a MIT license. It may also need some changes and bug fixes. And now I have dilemma; I might know that it works in the GPL package. I am not allowed to take a single line out of it, as GPL is virulent and would require also a change in that package.
In this case it would be better if I never read even one single line from this source. 
I don't know why the GPL was chosen here, but I lack background knowledge. Maybe a commercial product is planned, then I understand the motivation.  I would be pleased about the fact that there is also an OSS variant. 
But if the decision was made only from the gut, I would be happy about a revision. Maybe I would even engage, as it looks like the provider doesn't take care on authorization.

**Comment by Timo-Breumelhof** [comment]
ah, ok

**Comment by BarryWaluszko** [comment]
@Timo-Breumelhof  @SCullman thanks for your input. I've changed license to MIT. 
The first release is ready too. Please test this plugin, but be aware it's using OWIN pipeline that could be tricky in combination with DNN framework.
Waiting for your feedback.

**Comment by Timo-Breumelhof** [comment]
Cool :-)

**Comment by SCullman** [comment]
Thank you very much. I will do!
